### ISSUE TITLE
Does not build on Xcode ~10.1

### ISSUE THREAD

**Issue by ericvicenti** [zachwaugh/hues#1]
You are so awesome for releasing this! I used Hues many years ago, and I'm happy to see it released here for posterity.

Unfortunately I can't get it to build on the latest Mohave Xcode, I tried upgrading the xib files and changing the macOS Deployment Target to 10.12, yet the following still occurs:

<img width="1512" alt="screen shot 2018-11-14 at 7 08 34 pm" src="https://user-images.githubusercontent.com/1483597/48527649-c0808800-e840-11e8-9ee3-6865a6c845e9.png">

Again, thank you for open-sourcing Hues!

**Comment by zachwaugh** [comment]
Hey @ericvicenti, thanks! I totally missed this issue earlier. I just pushed a fix for this. It should build now with Xcode 10, but I didn't test that anything else isn't broken.
